package main.rendering;

public enum RenderingLayer {
    RENDERING_LAYER_HUD_TOP,
    RENDERING_LAYER_HUD_MIDDLE,
    RENDERING_LAYER_HUD_BOTTOM,

    RENDERING_LAYER_FLYING_TOP,
    RENDERING_LAYER_FLYING_MIDDLE,
    RENDERING_LAYER_FLYING_BOTTOM,

    RENDERING_LAYER_LEAVES_TOP,
    RENDERING_LAYER_LEAVES_MIDDLE,
    RENDERING_LAYER_LEAVES_BOTTOM,

    RENDERING_LAYER_TURRET_TOP,
    RENDERING_LAYER_TURRET_MIDDLE,
    RENDERING_LAYER_TURRET_BOTTOM,

    RENDERING_LAYER_GROUND_TOP,
    RENDERING_LAYER_GROUND_MIDDLE,
    RENDERING_LAYER_GROUND_BOTTOM,

    RENDERING_LAYER_TERRAIN_TOP,
    RENDERING_LAYER_TERRAIN_MIDDLE,
    RENDERING_LAYER_TERRAIN_BOTTOM
}
