package main.game.characters;

public enum LifeStates {
    CURRENTLY_ALIVE,
    CURRENTLY_DEAD,
    CURRENTLY_IDLE,
    CURRENTLY_DEPLOYING,
    CURRENTLY_RETRACTING,
    CURRENTLY_PURSUING,
    CURRENTLY_ATTACKING
}
