package main.game.level;

import main.utils.data.Config;
import main.utils.noise.PseudoRandom;
import main.utils.vectors.IVec2;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

public class LevelGenerator {
    public static char[][] genTerrain(IVec2 size){
        char[][] output=new char[size.y][size.x];
        for(int x=0;x<size.x;x++){
            for(int y=0;y<size.y;y++){
                if(PseudoRandom.isRandomBetween(-0.05,0.05,-x+50,30+y, Config.noiseSizeTerrainPath)){
                    output[y][x]='P';
                    continue;
                }
                if(PseudoRandom.isRandomBetween(0,0.1,x+5,3-y, Config.noiseSizeTerrainStones)){
                    output[y][x]='R';
                    continue;
                }
                if(PseudoRandom.isRandomBetween(0.45,0.55,2-x,3-y, Config.noiseSizeTerrainTrees)){
                    output[y][x]='T';
                    continue;
                }
                if(PseudoRandom.isRandomBetween(0,0.0005,30*x,3-20*y, Config.noiseSizeTerrainTraps)){
                    output[y][x]='0';
                    continue;
                }
                if(PseudoRandom.isRandomBetween(0,0.0005,-25*x,3-25*y, Config.noiseSizeTerrainTraps)){
                    output[y][x]='1';
                    continue;
                }
                output[y][x]='.';
            }
        }
        writeMap(output);
        return output;
    }

    private static void writeMap(char[][] map){
        try {
            PrintWriter printWriter= new PrintWriter(new FileWriter("assets/data/autoGeneratedLevel.txt"));
            for (char[] chars : map) {
                for (int x = 0; x < map[0].length; x++) {
                    printWriter.write(chars[x]);
                }
                printWriter.write('\n');
            }
            printWriter.close();
        } catch (IOException e) {
            System.out.println(e.getStackTrace());
        }
    }
}
