package main.physics;

public enum CollisionLayer {
    COLLISION_LAYER_TERRAIN,
    COLLISION_LAYER_ALLIES,
    COLLISION_LAYER_ENNEMIES,
    COLLISION_LAYER_ALLY_PROJECTILES,
    COLLISION_LAYER_ENNEMY_PROJECTILES;
}
