package main.physics;

public enum ColliderType {
    SOLID_INERT,
    SOLID_THICK_INERT,
    SOLID_DAMAGE_DEALER,
    SOLID_THICK_DAMAGE_DEALER,
    SOLID_TRIGGER,
    SOLID_THICK_TRIGGER,

    AERIAL_INERT,
    AERIAL_DAMAGE_DEALER,
    AERIAL_THICK_INERT,
    AERIAL_THICK_DAMAGE_DEALER,
    AERIAL_TRIGGER,
    AERIAL_THICK_TRIGGER,

    POINT_INERT,
    POINT_DAMAGE_DEALER,
    POINT_TRIGGER
}
